### ISSUE TITLE
What is the goal of this repo?

### ISSUE THREAD

**Issue by CodeMan99** [zkat/make-fetch-happen#2]
Could someone please clarify why this project was started?

The package.json already includes (the very good) [node-fetch](https://github.com/bitinn/node-fetch) tool as a dependancy.

Based purely on the npmjs mailing list article, and the [README feature list](https://github.com/zkat/make-fetch-happen#features) I am unable to tell why the project was started.

Note that I am not nocking here, I am honestly curious so that I can determine if or how I can contribute.

**Comment by VictorioBerra** [comment]
Was just about to ask whats wrong with [node-fetch](https://github.com/bitinn/node-fetch)?

**Comment by zkat** [comment]
@CodeMan99 @VictorioBerra `node-fetch` is explicitly designed to be fairly unopinionated and minimalist in its implementation. `make-fetch-happen` is strictly a wrapper around `node-fetch` that adds a bunch of other bits from the `fetch` API that wouldn't really make sense to have in the "generic" server-side `fetch` implementation: caching, automatic retries, simplified proxy configuration, a default cookie jar, automatic keep-alive/http agents.

*some* of those things are possibly things `node-fetch` wants to provide hooks into: `make-fetch-happen` saves you the trouble of providing those hooks yourself. :)

I'll leave this issue open a bit to answer any further questions. I hope it's clear enough that this project is not meant to supersede `node-fetch`, but to in fact build on it for the subset of people whose needs happen to align with what `make-fetch-happen` does: it does what *I* need it to do.

**Comment by CodeMan99** [comment]
Perhaps this info should be presented in the README?

**Comment by zkat** [comment]
@CodeMan99 maybe? The README seems pretty explicit to me, as you read it, that it's a wrapper _around_ `node-fetch`. Even the first bullet point in the feature list mentions that. There's a section explicitly about options handled by node-fetch, etc. Is there a particular edit you'd suggest?

Note that the README has gotten more filled out, along with the featureset, since you made this issue, so it might be worth reviewing again. :)

**Comment by CodeMan99** [comment]
Yeah, I did see the improvements. Perhaps my feeling is a non-issue.

Anyway, should you decide to add more info, I would like to see a small narrative before (or in) the [#features](https://github.com/zkat/make-fetch-happen#features) block.

To me anyway, your first reply seemed a little bit more revealing than the references the README has currently.

**Comment by zkat** [comment]
#20 should address this. I'll merge it later if no one comments on it.
