### ISSUE TITLE
Fix test suite on node@8

### ISSUE THREAD

**Issue by zkat** [zkat/make-fetch-happen#33]
I honestly don't even know _why_ it's failing, but the test suite is definitely not working on node@8. I did notice that `node-fetch-npm` is also failing on node@8 but only one hook -- I don't know if that would be the full source of all the errors on our end.

**Comment by zcei** [comment]
I think it's related to `nock` not intercepting properly with the changes in Node 8 APIs. There is https://github.com/node-nock/nock/pull/929 to fix this.
