### ISSUE TITLE
`timeout` option doesn't seem to be respected

### ISSUE THREAD

**Issue by Lange** [zkat/make-fetch-happen#35]
Hello! :wave:

I'm using `make-fetch-happen` in some tests. These tests involve uploading very large ZIP files, then waiting for a long time as the server processes these ZIP files, then finally getting a response.

`make-fetch-happen` was timing out in the period after the upload finished but while it was still waiting for this response. I tried providing a `timeout` value, but that didn't help. I did some digging, and realized that the `agentkeepalive` used by `make-fetch-happen` sets its own timeout, and that `make-fetch-happen` was not passing my desired timeout on to `agentkeepalive`.

I believe that the fix is to add `timeout: opts.timeout` to the `HttpsAgent` and `HttpAgent` constructors in [latest/agent.js#L47-L57](https://github.com/zkat/make-fetch-happen/blob/latest/agent.js#L47-L57). There may also be other options that should be forwarded to these constructors, but I am not knowledgeable enough on this topic to say for sure.

Thanks for this module!

**Comment by zkat** [comment]
You wanna give that patch a whirl and see if it does the trick? :)

**Comment by Lange** [comment]
Sure! I'll see what I can do in the morning.

**Comment by Lange** [comment]
Hm, I'm having a few issues:

1. If the `timeout` option is indeed not being properly respected, then I'm unsure how or why the current `timeout` tests are passing.
2. A fresh clone of `make-fetch-happen` fails tests on the following system configurations for me:
  - Windows 10 x64, Node v8.1.2, npm v5.3.0
  - Ubuntu 16.04.2 x64, Node v.8.2.1, npm v5.3.0

I see that the current test matrix does not include Node 8 -- is it a known issue that tests don't pass on Node 8? Could I have something weird in my system configurations that might be causing these failures?

**Comment by Lange** [comment]
Ah gosh I'm sorry, I just saw https://github.com/zkat/make-fetch-happen/issues/33. I'll work under node 7 for now.

**Comment by Lange** [comment]
Okay, I think I might understand the issue:

I believe that there are multiple timeout timers in play. The current tests only test for very short timers. These tests pass, because `agentkeepalive` defaults its own timeout to 30 seconds. Any test under this duration would pass. It is only when a test needs to exceed a duration of 30 seconds that this other, unaccounted for timeout would fire, causing the test to fail.

I'm unsure if my initial suggestion of just forwarding the `opts.timeout` parameter to `agentkeepalive` is wise, or if a more substantial refactoring to reduce the number of competing timeout mechanisms is called for. Perhaps completely disabling the timeout in `agentkeepalive` is needed?

**Comment by zkat** [comment]
It looks like `agentkeepalive` has two kinds of sockets with their own individual timeout settings?

The `timeout` setting itself is what acts on "working" sockets (aka sockets that have a current http request running, vs "free" sockets that are waiting for a new request to start), so I think it's actually totally fine to set _both_ the `node-fetch-npm` timeout _and_ the `agentkeepalive` timeout. There's a chance one might win vs the other, but also you could just set one to be timeout+1 to make sure we get the timeout error from the same place every time: my instinct is to make sure we catch `ETIMEDOUT` regardless of whether it's from the agent or from node-fetch, though, because 👋 concurrency 👋 .

**Comment by Lange** [comment]
I've been trying to add tests for my change. I have never used `tap` before so I'm not really sure what its error output here means. I've tried to read the docs and search for more info, but I'm not really sure what my test is doing wrong here.

Here is my rudimentary test:
```js
test('what', {timeout: 40000}, t => {
  const srv = tnock(t, HOST)
  srv.get('/test').delay(31000).reply(200, CONTENT)
  return fetch(`${HOST}/test`, {
    timeout: 35000,
    retry: { retries: 0 }
  })
})
```

And here is the output I get from `npm t`:
```
> make-fetch-happen@2.4.13 pretest C:\Users\vanca\Documents\Programming\make-fetch-happen
> standard lib test *.js


> make-fetch-happen@2.4.13 test C:\Users\vanca\Documents\Programming\make-fetch-happen
> nyc --all -- tap -J test/*.js

test/agent.js ......................................... 2/2 501ms
test/cache.js ..................................... 137/139
  ~ supports range caching (partial requests)
  ~ Support Cache object injection

test/fetch.js ....................................... 34/36 30s
  not ok test count !== plan
    +++ found                                                           
    --- wanted                                                          
    -1                                                                  
    +20                                                                 
    results:
      ok: false
      count: 20
      pass: 20
      fail: 1
      bailout: false
      todo: 1
      skip: 0
      plan:
        start: null
        end: null
        skipAll: false
        skipReason: ''
        comment: ''
      failures:
        - tapError: no plan

  ~ supports automatic agent pooling on unique configs

test/integrity.js ................................... 12/12
total ............................................. 185/189


  185 passing (30s)
  3 pending
  1 failing
```
