### ISSUE TITLE
Security advisory on http-proxy-agent & https-proxy-agent

### ISSUE THREAD

**Issue by ghost** [zkat/make-fetch-happen#53]
The joys of npm audit :)

https://nodesecurity.io/advisories/607 
Versions of http-proxy-agent before 2.1.0 are vulnerable to denial of service and uninitialized memory leak when unsanitized options are passed to Buffer.

https://nodesecurity.io/advisories/593 
Versions of http-proxy-agent before 2.1.0 are vulnerable to denial of service and uninitialized memory leak when unsanitized options are passed to Buffer.

Txs

**Comment by SimenB** [comment]
This repo uses 2.1.0 or newer for both, though?

https://github.com/zkat/make-fetch-happen/blob/508c0af20e02f86445fc9b278382abac811f0393/package.json#L39-L40

**Comment by ghost** [comment]
You're right, npm-profile is the issue.  txs

**Comment by CuAnnan** [comment]
Yeah, sorry about that. Was about to close.
