### ISSUE TITLE
Default retry behavior

### ISSUE THREAD

**Issue by gtramontina** [zkat/make-fetch-happen#57]
Hello there! First of all, thank you for putting this module together. Enabling caching is a much needed addition to `fetch`.

One thing I noticed, though, is the default retry behavior. If no `retry` options are configured, `make-fetch-happen` will end up using the [default values that `promise-retry`](https://www.npmjs.com/package/promise-retry#promiseretryfn-options) sets (`10` at the time of this writing). I'm not sure if this is intended or not, but it bit me quite hard, as I was not expecting any retry unless explicitly configured.

I'd be happy to submit a PR either making this explicit in the documentation or "fixing" it (which, at this point, should be considered a breaking change).

Thoughts? 💭

**Comment by zkat** [comment]
tbh, retrying is one of the core features of this library -- it won't retry things that "shouldn't" be retried (such as POSTs), but it's intended to be HTTP-compliant on this front.

It's possible that the default retries are a bit _too_ aggressive, but I'm inclined towards having the library try _pretty hard_ to retry, by default, even if it slows things down a lot.

How did it bite you, specifically? Was it just that it took a long time?

**Comment by gtramontina** [comment]
Yeah… my tests were timing out because the requests "never ended". This is probably because I failed to read the readme thoroughly (where it says: `Automatic HTTP-semantics-aware request retries`) and was expecting `make-fetch-happen` to behave as similar to `fetch` as possible unless configured differently. Thanks for clarifying, though! I'll close this issue. Sorry about this. 😄

**Comment by zkat** [comment]
No worries. It's good feedback!

Defaulting the retry object can be a bit tricky but if you're interested in providing better defaults, please go ahead and pr it! Having the retries take so long by default that it starts timing out tests is probably not what we want, after all.
