### ISSUE TITLE
Release 5.0.0 missing from GitHub releases

### ISSUE THREAD

**Issue by trivikr** [zkat/make-fetch-happen#69]
This was pointed out in https://github.com/lerna/lerna-changelog/pull/142#issuecomment-536295201

- As per npmjs, v5.0.0 of make-fetch-happen was released 2 months ago ([link](https://www.npmjs.com/package/make-fetch-happen))
- However, this version is not visible in GitHub releases ([link](https://github.com/zkat/make-fetch-happen/releases))

Is there some place we can view release notes for v5.0.0?

**Comment by isaacs** [comment]
https://github.com/npm/make-fetch-happen/blob/latest/CHANGELOG.md
